import Foundation

/// Codessa's own curated plugin marketplace — the "Discover" tab. These are
/// recommended MCP servers users can add, distinct from plugins imported from
/// other coding agents (grok/Claude/Codex/Cursor), which live on the Import tab.
enum MarketplaceCatalog {
    /// Curated entries. `sourceTool == .builtin` marks them as Codessa's catalogue.
    static let plugins: [Plugin] = [
        make("context7", "Context7", "book.closed",
             "Up-to-date documentation for any library, injected straight into context.",
             cmd: "npx", args: ["-y", "@upstash/context7-mcp"]),
        make("github", "GitHub", "chevron.left.forwardslash.chevron.right",
             "Browse repos, manage issues and pull requests.",
             cmd: "npx", args: ["-y", "@modelcontextprotocol/server-github"]),
        make("filesystem", "Filesystem", "folder",
             "Read and write local files within an allowed directory.",
             cmd: "npx", args: ["-y", "@modelcontextprotocol/server-filesystem"]),
        make("playwright", "Playwright", "cursorarrow.rays",
             "Drive a real Chrome browser for testing and scraping.",
             cmd: "npx", args: ["-y", "@playwright/mcp@latest"]),
        make("supabase", "Supabase", "cylinder.split.1x2",
             "Query and manage your Supabase Postgres database.",
             cmd: "npx", args: ["-y", "@supabase/mcp-server-supabase@latest"]),
        make("postgres", "PostgreSQL", "cylinder",
             "Run read-only SQL against any Postgres connection.",
             cmd: "npx", args: ["-y", "@modelcontextprotocol/server-postgres"]),
        make("sentry", "Sentry", "exclamationmark.triangle",
             "Inspect errors, issues and performance from Sentry.",
             url: "https://mcp.sentry.dev/mcp"),
        make("linear", "Linear", "checklist",
             "Create, search and update Linear issues.",
             url: "https://mcp.linear.app/sse"),
        make("notion", "Notion", "doc.richtext",
             "Search and edit pages across your Notion workspace.",
             cmd: "npx", args: ["-y", "@notionhq/notion-mcp-server"]),
        make("slack", "Slack", "message",
             "Read channels and post messages to Slack.",
             cmd: "npx", args: ["-y", "@modelcontextprotocol/server-slack"]),
        make("brave-search", "Brave Search", "magnifyingglass",
             "Live web search results via the Brave API.",
             cmd: "npx", args: ["-y", "@modelcontextprotocol/server-brave-search"]),
        make("stripe", "Stripe", "creditcard",
             "Look up customers, payments and invoices in Stripe.",
             cmd: "npx", args: ["-y", "@stripe/mcp"]),
        make("memory", "Memory", "brain",
             "A persistent knowledge graph the agent can read and write.",
             cmd: "npx", args: ["-y", "@modelcontextprotocol/server-memory"]),
        make("sequential-thinking", "Sequential Thinking", "list.number",
             "A structured, step-by-step reasoning scratchpad.",
             cmd: "npx", args: ["-y", "@modelcontextprotocol/server-sequential-thinking"]),
        make("fetch", "Fetch", "arrow.down.circle",
             "Fetch any URL and convert the page to clean markdown.",
             cmd: "uvx", args: ["mcp-server-fetch"]),
        make("puppeteer", "Puppeteer", "cursorarrow.motionlines",
             "Headless Chrome automation for scraping and screenshots.",
             cmd: "npx", args: ["-y", "@modelcontextprotocol/server-puppeteer"]),
        make("gitlab", "GitLab", "chevron.left.forwardslash.chevron.right",
             "Manage GitLab projects, issues and merge requests.",
             cmd: "npx", args: ["-y", "@modelcontextprotocol/server-gitlab"]),
        make("google-drive", "Google Drive", "doc.on.doc",
             "Search and read documents from Google Drive.",
             cmd: "npx", args: ["-y", "@modelcontextprotocol/server-gdrive"]),
        make("google-maps", "Google Maps", "map",
             "Geocoding, directions and place search.",
             cmd: "npx", args: ["-y", "@modelcontextprotocol/server-google-maps"]),
        make("sqlite", "SQLite", "tablecells",
             "Query and explore a local SQLite database.",
             cmd: "uvx", args: ["mcp-server-sqlite"]),
        make("figma", "Figma", "pencil.and.ruler",
             "Pull frames, components and styles from your Figma files.",
             cmd: "npx", args: ["-y", "figma-developer-mcp", "--stdio"]),
        make("firecrawl", "Firecrawl", "flame",
             "Crawl and scrape whole websites into structured data.",
             cmd: "npx", args: ["-y", "firecrawl-mcp"]),
        make("exa", "Exa Search", "sparkle",
             "Neural web search built for AI agents.",
             cmd: "npx", args: ["-y", "exa-mcp-server"]),
        make("tavily", "Tavily", "globe",
             "Real-time web search and content extraction.",
             cmd: "npx", args: ["-y", "tavily-mcp"]),
        make("perplexity", "Perplexity", "bubble.left.and.text.bubble.right",
             "Ask Perplexity for cited, up-to-date answers.",
             cmd: "npx", args: ["-y", "server-perplexity-ask"]),
        make("neon", "Neon", "bolt",
             "Manage serverless Postgres branches on Neon.",
             cmd: "npx", args: ["-y", "@neondatabase/mcp-server-neon", "start"]),
        make("cloudflare", "Cloudflare", "cloud",
             "Manage Workers, KV, R2, D1 and DNS on Cloudflare.",
             cmd: "npx", args: ["-y", "@cloudflare/mcp-server-cloudflare"]),
        make("atlassian", "Atlassian", "checkmark.seal",
             "Jira issues and Confluence pages, hosted by Atlassian.",
             url: "https://mcp.atlassian.com/v1/sse"),
        make("obsidian", "Obsidian", "doc.text",
             "Read and search notes in your Obsidian vault.",
             cmd: "npx", args: ["-y", "obsidian-mcp"]),
        make("youtube", "YouTube", "play.rectangle",
             "Fetch transcripts and metadata from YouTube videos.",
             cmd: "npx", args: ["-y", "@anaisbetts/mcp-youtube"]),
        make("e2b", "E2B", "terminal",
             "Run code in a secure cloud sandbox.",
             cmd: "npx", args: ["-y", "@e2b/mcp-server"]),
        make("apify", "Apify", "ant",
             "Run Apify Actors to scrape sites and apps at scale.",
             cmd: "npx", args: ["-y", "@apify/actors-mcp-server"]),
    ]

    private static func make(_ id: String, _ name: String, _ icon: String, _ detail: String,
                             cmd: String? = nil, args: [String] = [], url: String? = nil) -> Plugin {
        Plugin(
            id: "marketplace:\(id)",
            name: name,
            kind: .mcpServer,
            sourceTool: .builtin,
            detail: detail,
            iconSystemName: icon,
            command: cmd,
            url: url,
            args: args
        )
    }
}
